export interface Location {
  id: string;
  name: string;
  slug: string;
  county: string;
  description: string;
  businessFocus?: string;
  nearbyAreas?: string[];
  population?: string;
  keyIndustries?: string[];
}

export const locations: Location[] = [
  {
    id: 'watford',
    name: 'Watford',
    slug: 'watford',
    county: 'Hertfordshire',
    description: 'Watford is a vibrant town in Hertfordshire, known for its excellent transport links to London, thriving business community, and diverse economy. With a mix of retail, service, and technology businesses, Watford offers a dynamic environment for companies looking to establish or expand their online presence.',
    businessFocus: 'Watford has a diverse business landscape with a strong retail sector, professional services, and growing technology companies. The town center hosts numerous small to medium-sized businesses that benefit from both local customers and visitors from surrounding areas.',
    nearbyAreas: ['Bushey', 'Rickmansworth', 'Borehamwood', 'St. Albans'],
    population: 'Approximately 96,800',
    keyIndustries: ['Retail', 'Professional Services', 'Technology', 'Healthcare', 'Entertainment'],
  },
  {
    id: 'hemel-hempstead',
    name: 'Hemel Hempstead',
    slug: 'hemel-hempstead',
    county: 'Hertfordshire',
    description: 'Hemel Hempstead is a thriving new town in Hertfordshire with a strong business presence, particularly in the industrial and commercial sectors. Its strategic location near the M1 and M25 motorways makes it an ideal location for businesses serving both local and national markets.',
    businessFocus: 'Hemel Hempstead features several business parks and industrial areas, including Maylands Business Park, which is home to numerous companies across various sectors. The town has a mix of large corporations and small to medium enterprises.',
    nearbyAreas: ['St. Albans', 'Berkhamsted', 'Kings Langley', 'Tring'],
    population: 'Approximately 97,500',
    keyIndustries: ['Manufacturing', 'Logistics', 'Technology', 'Retail', 'Construction'],
  },
  {
    id: 'stevenage',
    name: 'Stevenage',
    slug: 'stevenage',
    county: 'Hertfordshire',
    description: 'Stevenage is a significant town in Hertfordshire with a strong heritage in technology and engineering. As the first new town designated under the New Towns Act 1946, it has developed into an important commercial center with excellent transport links and a diverse business community.',
    businessFocus: 'Stevenage is known for its technology and engineering sectors, with several major companies having headquarters or significant operations in the area. The Stevenage Bioscience Catalyst and Gunnels Wood industrial area are key business hubs.',
    nearbyAreas: ['Hitchin', 'Letchworth Garden City', 'Welwyn Garden City', 'Knebworth'],
    population: 'Approximately 87,800',
    keyIndustries: ['Aerospace', 'Pharmaceuticals', 'Biotechnology', 'Engineering', 'Technology'],
  },
  {
    id: 'st-albans',
    name: 'St. Albans',
    slug: 'st-albans',
    county: 'Hertfordshire',
    description: 'St. Albans is a historic cathedral city in Hertfordshire with a thriving business community and strong connections to London. Known for its rich Roman history, beautiful architecture, and vibrant city center, St. Albans attracts both tourists and businesses looking for a prestigious location with excellent amenities.',
    businessFocus: 'St. Albans has a diverse business ecosystem with a strong presence in professional services, retail, and hospitality. The city center features numerous independent businesses alongside national chains, creating a dynamic commercial environment.',
    nearbyAreas: ['Harpenden', 'Hatfield', 'Hemel Hempstead', 'Radlett'],
    population: 'Approximately 147,000',
    keyIndustries: ['Professional Services', 'Finance', 'Retail', 'Hospitality', 'Education'],
  },
  {
    id: 'bishops-stortford',
    name: 'Bishop\'s Stortford',
    slug: 'bishops-stortford',
    county: 'Hertfordshire',
    description: 'Bishop\'s Stortford is a historic market town in Hertfordshire, located near Stansted Airport. Its strategic location and excellent transport links make it an attractive location for businesses, particularly those in the service and logistics sectors.',
    businessFocus: 'Bishop\'s Stortford benefits from its proximity to Stansted Airport, which has fostered growth in travel-related businesses, logistics, and hospitality. The town center hosts numerous independent retailers and service providers.',
    nearbyAreas: ['Sawbridgeworth', 'Stansted Mountfitchet', 'Great Dunmow', 'Harlow'],
    population: 'Approximately 40,000',
    keyIndustries: ['Aviation Services', 'Logistics', 'Retail', 'Hospitality', 'Professional Services'],
  },
  {
    id: 'cheshunt',
    name: 'Cheshunt',
    slug: 'cheshunt',
    county: 'Hertfordshire',
    description: 'Cheshunt is a growing town in the Borough of Broxbourne, Hertfordshire, with good connections to London. Its location in the Lea Valley has historically supported a range of industries, and today it continues to be an important commercial center in the region.',
    businessFocus: 'Cheshunt has a mix of retail, service, and light industrial businesses. The Brookfield Centre is a major retail destination, while Delamare Road hosts various commercial enterprises.',
    nearbyAreas: ['Waltham Cross', 'Hoddesdon', 'Enfield', 'Waltham Abbey'],
    population: 'Approximately 52,000',
    keyIndustries: ['Retail', 'Horticulture', 'Light Manufacturing', 'Logistics', 'Services'],
  },
  {
    id: 'letchworth-garden-city',
    name: 'Letchworth Garden City',
    slug: 'letchworth-garden-city',
    county: 'Hertfordshire',
    description: 'Letchworth Garden City is the world\'s first garden city, combining urban amenities with green spaces. This unique heritage has created a distinctive business environment that attracts companies looking for a high quality of life for their employees alongside good business facilities.',
    businessFocus: 'Letchworth has several business areas including the Spirella Building and Works Road industrial area. The town has a tradition of manufacturing and engineering, alongside newer technology and service businesses.',
    nearbyAreas: ['Hitchin', 'Baldock', 'Stevenage', 'Biggleswade'],
    population: 'Approximately 33,600',
    keyIndustries: ['Manufacturing', 'Engineering', 'Technology', 'Creative Industries', 'Retail'],
  },
  {
    id: 'hatfield',
    name: 'Hatfield',
    slug: 'hatfield',
    county: 'Hertfordshire',
    description: 'Hatfield is a town in Hertfordshire with a strong aerospace heritage and home to the University of Hertfordshire. This educational presence, combined with good transport links and business parks, makes Hatfield an important center for knowledge-based industries and technology companies.',
    businessFocus: 'Hatfield Business Park, built on the former site of Hatfield Aerodrome, is a major commercial center. The presence of the University of Hertfordshire has fostered growth in research, technology, and education-related businesses.',
    nearbyAreas: ['Welwyn Garden City', 'St. Albans', 'Potters Bar', 'Welham Green'],
    population: 'Approximately 39,000',
    keyIndustries: ['Aerospace', 'Technology', 'Education', 'Research', 'Retail'],
  },
  {
    id: 'hertford',
    name: 'Hertford',
    slug: 'hertford',
    county: 'Hertfordshire',
    description: 'Hertford is the historic county town of Hertfordshire, combining heritage with a vibrant modern business community. Its picturesque setting, good schools, and quality of life make it attractive to businesses and professionals looking for a balance between work and lifestyle.',
    businessFocus: 'Hertford has a diverse business community with a strong presence in professional services, retail, and hospitality. The town center features many independent businesses, while Hertford Business Park hosts larger companies.',
    nearbyAreas: ['Ware', 'Welwyn Garden City', 'Hoddesdon', 'Harlow'],
    population: 'Approximately 26,800',
    keyIndustries: ['Professional Services', 'Retail', 'Hospitality', 'Creative Industries', 'Education'],
  },
  {
    id: 'hitchin',
    name: 'Hitchin',
    slug: 'hitchin',
    county: 'Hertfordshire',
    description: 'Hitchin is a historic market town in Hertfordshire with a thriving business community. Its charming town center, regular markets, and strong sense of community make it an attractive location for independent businesses and service providers.',
    businessFocus: 'Hitchin has a vibrant town center with numerous independent retailers, cafes, and service providers. The Wilbury Way industrial area hosts manufacturing and distribution businesses, while professional services are well-represented throughout the town.',
    nearbyAreas: ['Letchworth Garden City', 'Stevenage', 'Baldock', 'Luton'],
    population: 'Approximately 33,350',
    keyIndustries: ['Retail', 'Professional Services', 'Hospitality', 'Manufacturing', 'Creative Industries'],
  },
  {
    id: 'potters-bar',
    name: 'Potters Bar',
    slug: 'potters-bar',
    county: 'Hertfordshire',
    description: 'Potters Bar is a town in Hertfordshire with excellent transport links to London, making it a popular location for commuters and businesses serving the capital. Its suburban character and good amenities create an attractive environment for service-based businesses and professionals.',
    businessFocus: 'Potters Bar has a mix of retail and service businesses in its town center, alongside some light industrial areas. Its proximity to London has made it popular with businesses that serve clients in both Hertfordshire and the capital.',
    nearbyAreas: ['Barnet', 'Hatfield', 'Enfield', 'Brookmans Park'],
    population: 'Approximately 22,000',
    keyIndustries: ['Professional Services', 'Retail', 'Healthcare', 'Education', 'Technology'],
  },
  {
    id: 'bushey',
    name: 'Bushey',
    slug: 'bushey',
    county: 'Hertfordshire',
    description: 'Bushey is a town in Hertfordshire adjacent to Watford, offering a more residential character while benefiting from proximity to larger commercial centers. Its leafy suburbs and good schools make it attractive to professionals and service-based businesses.',
    businessFocus: 'Bushey has a range of small to medium-sized businesses, particularly in the service sector. The high street features independent retailers and service providers, while some larger businesses are located in dedicated commercial areas.',
    nearbyAreas: ['Watford', 'Stanmore', 'Borehamwood', 'Harrow'],
    population: 'Approximately 24,000',
    keyIndustries: ['Professional Services', 'Retail', 'Healthcare', 'Education', 'Creative Industries'],
  },
  {
    id: 'berkhamsted',
    name: 'Berkhamsted',
    slug: 'berkhamsted',
    county: 'Hertfordshire',
    description: 'Berkhamsted is a historic market town in Hertfordshire, known for its castle, canal, and vibrant high street. Its affluent character and strong sense of community make it particularly attractive to upscale retailers, service providers, and creative businesses.',
    businessFocus: 'Berkhamsted has a thriving high street with many independent businesses alongside some national chains. Professional services, creative industries, and hospitality are well-represented, catering to the town\'s affluent population.',
    nearbyAreas: ['Tring', 'Hemel Hempstead', 'Chesham', 'Amersham'],
    population: 'Approximately 18,500',
    keyIndustries: ['Retail', 'Professional Services', 'Creative Industries', 'Hospitality', 'Education'],
  },
  {
    id: 'harpenden',
    name: 'Harpenden',
    slug: 'harpenden',
    county: 'Hertfordshire',
    description: 'Harpenden is an affluent town in Hertfordshire with excellent transport links to London. Its combination of wealth, good schools, and attractive environment makes it a premium location for businesses serving high-end clients and professional services.',
    businessFocus: 'Harpenden\'s business community is dominated by retail, hospitality, and professional services. The town center features upscale shops, restaurants, and service providers catering to the town\'s affluent population.',
    nearbyAreas: ['St. Albans', 'Luton', 'Wheathampstead', 'Redbourn'],
    population: 'Approximately 30,240',
    keyIndustries: ['Professional Services', 'Finance', 'Retail', 'Hospitality', 'Education'],
  },
  {
    id: 'waltham-cross',
    name: 'Waltham Cross',
    slug: 'waltham-cross',
    county: 'Hertfordshire',
    description: 'Waltham Cross is a town in the Borough of Broxbourne, Hertfordshire, located at the edge of Greater London. Its strategic location near the M25 and proximity to London make it an important commercial center, particularly for logistics and distribution businesses.',
    businessFocus: 'Waltham Cross has a mix of retail, service, and industrial businesses. The Park Plaza and Lea Road industrial areas host numerous companies in manufacturing, distribution, and services.',
    nearbyAreas: ['Cheshunt', 'Enfield', 'Waltham Abbey', 'Hoddesdon'],
    population: 'Approximately 7,600',
    keyIndustries: ['Logistics', 'Retail', 'Manufacturing', 'Services', 'Construction'],
  },
  {
    id: 'radlett',
    name: 'Radlett',
    slug: 'radlett',
    county: 'Hertfordshire',
    description: 'Radlett is an affluent village in Hertfordshire, known for its upscale character and proximity to London. Its wealthy demographic and pleasant environment make it particularly suitable for premium service providers and businesses catering to high-net-worth individuals.',
    businessFocus: 'Radlett has a small but vibrant high street with independent retailers, restaurants, and service providers. Professional services such as financial advisors, legal firms, and property specialists are well-represented.',
    nearbyAreas: ['Borehamwood', 'St. Albans', 'Watford', 'Elstree'],
    population: 'Approximately 8,000',
    keyIndustries: ['Professional Services', 'Finance', 'Retail', 'Hospitality', 'Property'],
  },
  // NEW LOCATIONS - Adding all missing nearby areas
  {
    id: 'rickmansworth',
    name: 'Rickmansworth',
    slug: 'rickmansworth',
    county: 'Hertfordshire',
    description: 'Rickmansworth is an attractive market town in West Hertfordshire, known for its canals, historical architecture, and affluent residential areas. The town offers good transport links to London and hosts a variety of independent businesses alongside some national chains.',
    businessFocus: 'Rickmansworth has a strong local business community with independent retailers, cafes, restaurants, and professional services. The town center benefits from both local trade and tourism related to the canal networks.',
    nearbyAreas: ['Watford', 'Chorleywood', 'Northwood', 'Croxley Green'],
    population: 'Approximately 15,000',
    keyIndustries: ['Retail', 'Professional Services', 'Hospitality', 'Tourism', 'Healthcare'],
  },
  {
    id: 'borehamwood',
    name: 'Borehamwood',
    slug: 'borehamwood',
    county: 'Hertfordshire',
    description: 'Borehamwood is known as the home of the British film industry, with Elstree Studios being a major landmark. The town has excellent transport links to London and a diverse business community spanning entertainment, retail, and professional services.',
    businessFocus: 'Borehamwood\'s economy benefits from its connection to the film and television industry, with many production-related businesses. The town also has a strong retail sector and growing professional services community.',
    nearbyAreas: ['Elstree', 'Bushey', 'Radlett', 'Stanmore'],
    population: 'Approximately 32,000',
    keyIndustries: ['Entertainment', 'Media Production', 'Retail', 'Professional Services', 'Technology'],
  },
  {
    id: 'kings-langley',
    name: 'Kings Langley',
    slug: 'kings-langley',
    county: 'Hertfordshire',
    description: 'Kings Langley is a village in Hertfordshire with a rich history and strong community feel. Located between Hemel Hempstead and Watford, it offers a peaceful business environment with good transport connections to major commercial centers.',
    businessFocus: 'Kings Langley has a mix of local businesses serving the community, with a focus on independent retailers, professional services, and small enterprises. The village benefits from its proximity to larger business centers while maintaining its village character.',
    nearbyAreas: ['Hemel Hempstead', 'Watford', 'Berkhamsted', 'Abbots Langley'],
    population: 'Approximately 5,000',
    keyIndustries: ['Retail', 'Professional Services', 'Agriculture', 'Small Manufacturing', 'Services'],
  },
  {
    id: 'tring',
    name: 'Tring',
    slug: 'tring',
    county: 'Hertfordshire',
    description: 'Tring is a historic market town in Hertfordshire, situated at the foot of the Chiltern Hills. Known for its independent shops, restaurants, and strong community spirit, Tring offers an attractive location for businesses seeking a balance between accessibility and character.',
    businessFocus: 'Tring has a vibrant high street with many independent businesses, including boutique shops, restaurants, and professional services. The town attracts both local customers and visitors exploring the Chilterns area.',
    nearbyAreas: ['Berkhamsted', 'Hemel Hempstead', 'Aylesbury', 'Chesham'],
    population: 'Approximately 12,000',
    keyIndustries: ['Retail', 'Hospitality', 'Professional Services', 'Tourism', 'Agriculture'],
  },
  {
    id: 'knebworth',
    name: 'Knebworth',
    slug: 'knebworth',
    county: 'Hertfordshire',
    description: 'Knebworth is a village in Hertfordshire famous for its historic house and music festivals. Despite its village status, it has good transport links and serves as an attractive location for businesses seeking a prestigious address in a peaceful setting.',
    businessFocus: 'Knebworth\'s business community consists mainly of professional services, small businesses, and enterprises related to tourism and events. The village benefits from its prestigious reputation and proximity to larger commercial centers.',
    nearbyAreas: ['Stevenage', 'Hitchin', 'Welwyn Garden City', 'Hertford'],
    population: 'Approximately 1,500',
    keyIndustries: ['Professional Services', 'Event Management', 'Tourism', 'Retail', 'Property Services'],
  },
  {
    id: 'welwyn-garden-city',
    name: 'Welwyn Garden City',
    slug: 'welwyn-garden-city',
    county: 'Hertfordshire',
    description: 'Welwyn Garden City is a planned town in Hertfordshire, designed as a garden city with wide open spaces and modern amenities. It hosts numerous businesses and has excellent transport links, making it an attractive location for companies of all sizes.',
    businessFocus: 'Welwyn Garden City has several business parks and industrial areas, with a strong presence in manufacturing, technology, and professional services. The town center also features a good mix of retail and service businesses.',
    nearbyAreas: ['Hatfield', 'Hertford', 'Stevenage', 'Welham Green'],
    population: 'Approximately 51,000',
    keyIndustries: ['Manufacturing', 'Technology', 'Retail', 'Professional Services', 'Pharmaceuticals'],
  },
  {
    id: 'sawbridgeworth',
    name: 'Sawbridgeworth',
    slug: 'sawbridgeworth',
    county: 'Hertfordshire',
    description: 'Sawbridgeworth is a market town in East Hertfordshire with a rich history dating back to Saxon times. The town has maintained its historical character while developing modern business facilities, offering an attractive environment for various enterprises.',
    businessFocus: 'Sawbridgeworth has a strong local business community with independent shops, restaurants, and service providers. The town benefits from its proximity to both Harlow and Bishop\'s Stortford.',
    nearbyAreas: ['Bishop\'s Stortford', 'Harlow', 'Stansted Mountfitchet', 'Much Hadham'],
    population: 'Approximately 8,700',
    keyIndustries: ['Retail', 'Agriculture', 'Professional Services', 'Manufacturing', 'Hospitality'],
  },
  {
    id: 'stansted-mountfitchet',
    name: 'Stansted Mountfitchet',
    slug: 'stansted-mountfitchet',
    county: 'Essex',
    description: 'Stansted Mountfitchet is a village in Essex, close to Stansted Airport and the Hertfordshire border. Its proximity to the airport makes it attractive for aviation-related businesses and those needing good international connections.',
    businessFocus: 'The village benefits from its location near Stansted Airport, with businesses in aviation services, logistics, and hospitality. It also has a growing community of small businesses and professional services.',
    nearbyAreas: ['Bishop\'s Stortford', 'Sawbridgeworth', 'Stansted Airport', 'Great Dunmow'],
    population: 'Approximately 6,000',
    keyIndustries: ['Aviation Services', 'Logistics', 'Professional Services', 'Retail', 'Hospitality'],
  },
  {
    id: 'great-dunmow',
    name: 'Great Dunmow',
    slug: 'great-dunmow',
    county: 'Essex',
    description: 'Great Dunmow is a historic market town in Essex, close to the Hertfordshire border. Known for its traditional market and strong community, it offers a blend of historical charm and modern business opportunities.',
    businessFocus: 'Great Dunmow has a thriving high street with independent businesses, market traders, and various professional services. The town benefits from both local trade and its position on major transport routes.',
    nearbyAreas: ['Bishop\'s Stortford', 'Stansted Mountfitchet', 'Braintree', 'Chelmsford'],
    population: 'Approximately 8,000',
    keyIndustries: ['Retail', 'Agriculture', 'Professional Services', 'Manufacturing', 'Market Trading'],
  },
  {
    id: 'harlow',
    name: 'Harlow',
    slug: 'harlow',
    county: 'Essex',
    description: 'Harlow is a new town in Essex, designed as a post-war new town with modern infrastructure and business facilities. Its strategic location between London and Cambridge, with excellent transport links, makes it attractive for technology and business services companies.',
    businessFocus: 'Harlow is known for its technology sector, with several major companies and start-ups based in the area. The town has modern business parks and good facilities for companies of all sizes.',
    nearbyAreas: ['Bishop\'s Stortford', 'Sawbridgeworth', 'Hertford', 'Epping'],
    population: 'Approximately 87,000',
    keyIndustries: ['Technology', 'Professional Services', 'Retail', 'Healthcare', 'Education'],
  },
  {
    id: 'waltham-abbey',
    name: 'Waltham Abbey',
    slug: 'waltham-abbey',
    county: 'Essex',
    description: 'Waltham Abbey is a town in Essex on the Greenwich Meridian, between the M25 and Epping Forest. With its mix of historical significance and modern amenities, it provides an attractive location for businesses seeking proximity to London.',
    businessFocus: 'Waltham Abbey has a diverse business community with retail, professional services, and light industrial businesses. The town benefits from its strategic location and good transport links.',
    nearbyAreas: ['Cheshunt', 'Waltham Cross', 'Epping', 'Enfield'],
    population: 'Approximately 22,000',
    keyIndustries: ['Retail', 'Professional Services', 'Light Manufacturing', 'Logistics', 'Tourism'],
  },
  {
    id: 'biggleswade',
    name: 'Biggleswade',
    slug: 'biggleswade',
    county: 'Bedfordshire',
    description: 'Biggleswade is a market town in Bedfordshire, close to the Hertfordshire border. Known for its market heritage and good transport links, it offers attractive opportunities for businesses serving the wider region.',
    businessFocus: 'Biggleswade has a strong market tradition and local business community, with particular strength in agriculture-related industries, retail, and professional services.',
    nearbyAreas: ['Letchworth Garden City', 'Sandy', 'Bedford', 'Hitchin'],
    population: 'Approximately 16,500',
    keyIndustries: ['Agriculture', 'Retail', 'Professional Services', 'Manufacturing', 'Logistics'],
  },
  {
    id: 'baldock',
    name: 'Baldock',
    slug: 'baldock',
    county: 'Hertfordshire',
    description: 'Baldock is a historic market town in North Hertfordshire, known for its medieval street pattern and strong sense of community. The town offers a blend of traditional charm and modern business opportunities.',
    businessFocus: 'Baldock has a thriving high street with independent businesses, alongside some national chains. The town benefits from its location on the A1(M) and good rail connections.',
    nearbyAreas: ['Letchworth Garden City', 'Hitchin', 'Stevenage', 'Royston'],
    population: 'Approximately 10,000',
    keyIndustries: ['Retail', 'Professional Services', 'Manufacturing', 'Agriculture', 'Logistics'],
  },
  {
    id: 'welham-green',
    name: 'Welham Green',
    slug: 'welham-green',
    county: 'Hertfordshire',
    description: 'Welham Green is a village in Hertfordshire with good rail connections to London. Its residential character and proximity to business centers make it attractive for professionals and small businesses.',
    businessFocus: 'Welham Green has a small but active business community, mainly comprising local service providers, professional services, and small retail businesses serving the local community.',
    nearbyAreas: ['Hatfield', 'Welwyn Garden City', 'Potters Bar', 'Brookmans Park'],
    population: 'Approximately 3,500',
    keyIndustries: ['Professional Services', 'Retail', 'Healthcare', 'Education', 'Local Services'],
  },
  {
    id: 'ware',
    name: 'Ware',
    slug: 'ware',
    county: 'Hertfordshire',
    description: 'Ware is an ancient market town in Hertfordshire on the River Lea, with a rich history and strong business community. The town combines historical charm with modern amenities and good transport links.',
    businessFocus: 'Ware has a vibrant high street with a mix of independent and chain businesses. The town also has several business parks and industrial areas, supporting a diverse range of enterprises.',
    nearbyAreas: ['Hertford', 'Hoddesdon', 'Hertford Heath', 'Great Amwell'],
    population: 'Approximately 18,000',
    keyIndustries: ['Retail', 'Professional Services', 'Manufacturing', 'Technology', 'Hospitality'],
  },
  {
    id: 'luton',
    name: 'Luton',
    slug: 'luton',
    county: 'Bedfordshire',
    description: 'Luton is a large town in Bedfordshire with Luton Airport being a major economic driver. The town has a diverse business community and excellent transport links, making it attractive for various industries.',
    businessFocus: 'Luton\'s economy is significantly influenced by the airport, with strong sectors in aviation, logistics, and hospitality. The town also has a growing technology sector and diverse retail offerings.',
    nearbyAreas: ['Harpenden', 'Hitchin', 'Dunstable', 'St. Albans'],
    population: 'Approximately 213,000',
    keyIndustries: ['Aviation', 'Logistics', 'Technology', 'Retail', 'Manufacturing'],
  },
  {
    id: 'barnet',
    name: 'Barnet',
    slug: 'barnet',
    county: 'Greater London',
    description: 'Barnet is a suburban area in North London with good transport links and a thriving business community. Its location provides easy access to both central London and Hertfordshire, making it attractive for various businesses.',
    businessFocus: 'Barnet has a diverse business landscape with strong retail, professional services, and technology sectors. The area benefits from its proximity to London while maintaining a more suburban character.',
    nearbyAreas: ['Potters Bar', 'Enfield', 'Finchley', 'Edgware'],
    population: 'Approximately 86,000',
    keyIndustries: ['Professional Services', 'Retail', 'Technology', 'Healthcare', 'Education'],
  },
  {
    id: 'brookmans-park',
    name: 'Brookmans Park',
    slug: 'brookmans-park',
    county: 'Hertfordshire',
    description: 'Brookmans Park is an affluent residential area in Hertfordshire with good rail connections to London. Known for its upscale character, it attracts premium service providers and professionals.',
    businessFocus: 'Brookmans Park has a small but quality-focused business community, with professional services, boutique retail, and upscale service providers catering to the affluent local population.',
    nearbyAreas: ['Potters Bar', 'Welham Green', 'Hatfield', 'Cuffley'],
    population: 'Approximately 3,000',
    keyIndustries: ['Professional Services', 'Finance', 'Premium Retail', 'Healthcare', 'Property Services'],
  },
  {
    id: 'stanmore',
    name: 'Stanmore',
    slug: 'stanmore',
    county: 'Greater London',
    description: 'Stanmore is an affluent area in North West London with a village-like character. Its proximity to both London and Hertfordshire, combined with good transport links, makes it attractive for businesses and professionals.',
    businessFocus: 'Stanmore has a strong local business community with professional services, upscale retail, and hospitality businesses. The area benefits from both local trade and proximity to central London.',
    nearbyAreas: ['Bushey', 'Watford', 'Harrow', 'Edgware'],
    population: 'Approximately 15,000',
    keyIndustries: ['Professional Services', 'Retail', 'Healthcare', 'Finance', 'Property'],
  },
  {
    id: 'harrow',
    name: 'Harrow',
    slug: 'harrow',
    county: 'Greater London',
    description: 'Harrow is a large suburban area in North West London, known for Harrow School and its diverse business community. The area offers good transport links and a mix of residential and commercial opportunities.',
    businessFocus: 'Harrow has a diverse business community with strong retail, professional services, and education sectors. The presence of Harrow School adds to the area\'s educational excellence reputation.',
    nearbyAreas: ['Bushey', 'Stanmore', 'Pinner', 'Northwood'],
    population: 'Approximately 149,000',
    keyIndustries: ['Education', 'Professional Services', 'Retail', 'Healthcare', 'Financial Services'],
  },
  {
    id: 'chesham',
    name: 'Chesham',
    slug: 'chesham',
    county: 'Buckinghamshire',
    description: 'Chesham is a market town in the Chiltern Hills of Buckinghamshire, close to the Hertfordshire border. Known for its traditional market and beautiful surrounding countryside, it offers an attractive location for various businesses.',
    businessFocus: 'Chesham has a strong local business community with independent retailers, market traders, and professional services. The town benefits from tourism related to the Chiltern Hills.',
    nearbyAreas: ['Amersham', 'Berkhamsted', 'Rickmansworth', 'Tring'],
    population: 'Approximately 21,000',
    keyIndustries: ['Retail', 'Tourism', 'Professional Services', 'Agriculture', 'Manufacturing'],
  },
  {
    id: 'amersham',
    name: 'Amersham',
    slug: 'amersham',
    county: 'Buckinghamshire',
    description: 'Amersham is a historic market town in Buckinghamshire, consisting of Old Amersham with its medieval character and Amersham-on-the-Hill with modern amenities. The town offers excellent transport links to London.',
    businessFocus: 'Amersham has a diverse business community with a mix of traditional and modern enterprises. The town benefits from its heritage tourism while supporting contemporary business needs.',
    nearbyAreas: ['Chesham', 'Berkhamsted', 'Gerrards Cross', 'High Wycombe'],
    population: 'Approximately 17,000',
    keyIndustries: ['Professional Services', 'Retail', 'Tourism', 'Technology', 'Finance'],
  },
  {
    id: 'wheathampstead',
    name: 'Wheathampstead',
    slug: 'wheathampstead',
    county: 'Hertfordshire',
    description: 'Wheathampstead is a village in Hertfordshire with a rich history and strong community spirit. Located near St. Albans, it offers a peaceful business environment with good access to larger commercial centers.',
    businessFocus: 'Wheathampstead has a small but active business community focused on serving the local population, with independent retailers, professional services, and hospitality businesses.',
    nearbyAreas: ['St. Albans', 'Harpenden', 'Redbourn', 'Welwyn Garden City'],
    population: 'Approximately 6,000',
    keyIndustries: ['Professional Services', 'Retail', 'Agriculture', 'Hospitality', 'Local Services'],
  },
  {
    id: 'redbourn',
    name: 'Redbourn',
    slug: 'redbourn',
    county: 'Hertfordshire',
    description: 'Redbourn is a village in Hertfordshire with a strong community feel and good connections to both St. Albans and Luton. The village maintains its rural character while supporting various local businesses.',
    businessFocus: 'Redbourn has a close-knit business community with local shops, pubs, and service providers. The village benefits from its proximity to larger towns while maintaining its village character.',
    nearbyAreas: ['St. Albans', 'Harpenden', 'Hemel Hempstead', 'Wheathampstead'],
    population: 'Approximately 5,500',
    keyIndustries: ['Retail', 'Professional Services', 'Agriculture', 'Hospitality', 'Local Services'],
  },
  {
    id: 'elstree',
    name: 'Elstree',
    slug: 'elstree',
    county: 'Hertfordshire',
    description: 'Elstree is a village in Hertfordshire famous for Elstree Studios and its connection to the film and television industry. Despite its small size, it has significant economic importance in the entertainment sector.',
    businessFocus: 'Elstree\'s economy is dominated by the entertainment industry, with film and television production being major employers. The village also has various support services for the entertainment industry.',
    nearbyAreas: ['Borehamwood', 'Radlett', 'Bushey', 'Watford'],
    population: 'Approximately 5,000',
    keyIndustries: ['Entertainment', 'Media Production', 'Professional Services', 'Tourism', 'Creative Industries'],
  },
  {
    id: 'enfield',
    name: 'Enfield',
    slug: 'enfield',
    county: 'Greater London',
    description: 'Enfield is a large suburban area in North London with a diverse business community and good transport links. Its location provides easy access to both central London and Hertfordshire.',
    businessFocus: 'Enfield has a broad business base including retail, manufacturing, professional services, and technology. The area benefits from its strategic location and diverse population.',
    nearbyAreas: ['Potters Bar', 'Cheshunt', 'Barnet', 'Waltham Cross'],
    population: 'Approximately 156,000',
    keyIndustries: ['Manufacturing', 'Retail', 'Professional Services', 'Technology', 'Healthcare'],
  },
  {
    id: 'hoddesdon',
    name: 'Hoddesdon',
    slug: 'hoddesdon',
    county: 'Hertfordshire',
    description: 'Hoddesdon is a town in the Borough of Broxbourne, Hertfordshire, located in the Lea Valley. The town has good transport links and a mix of residential and commercial areas.',
    businessFocus: 'Hoddesdon has a diverse business community with retail, professional services, and some light industry. The town center has undergone recent regeneration to support local businesses.',
    nearbyAreas: ['Waltham Cross', 'Cheshunt', 'Hertford', 'Ware'],
    population: 'Approximately 42,000',
    keyIndustries: ['Retail', 'Professional Services', 'Technology', 'Manufacturing', 'Logistics'],
  },
];

export function getAllLocationSlugs() {
  return locations.map(location => location.slug);
}

export function getLocationBySlug(slug: string) {
  return locations.find(location => location.slug === slug);
}
