export interface BusinessLandscape {
  /** Local Authority District the town sits inside (where the data is reported). */
  localAuthority: string;
  /** Total business units in the LAD per ONS UK Business Counts. */
  totalBusinesses: number;
  /** Year of the ONS reading (e.g. 2025). */
  year: number;
  /** Percentage of those businesses that are micro (0-9 employees). 0-100. */
  microBusinessPct: number;
  /** Top sectors by business unit count (display 4-6). */
  topSectors: { label: string; count: number }[];
  /** Citation URL — must link to the published ONS dataset. */
  sourceUrl: string;
  /** Postcode-specific Companies House counts (optional). */
  postcodeActiveCompanies?: number;
  postcodeNewLast12Months?: number;
  /** ISO date when the Companies House counts were pulled. */
  companiesHouseAsOf?: string;
}

export interface CommercialArea {
  name: string;
  type: string;
  description: string;
}

export interface TownFAQ {
  question: string;
  answer: string;
}

export interface Location {
  id: string;
  name: string;
  slug: string;
  county: string;
  description: string;
  businessFocus?: string;
  nearbyAreas?: string[];
  population?: string;
  keyIndustries?: string[];
  webDesignFocus?: string;
  webDesignBenefits?: string[];
  /** Research-driven content. Only populated for priority pages. */
  businessLandscape?: BusinessLandscape;
  commercialAreas?: CommercialArea[];
  townFAQs?: TownFAQ[];
  /** Postcode area covered (e.g. "SG6"). Shown alongside the landscape block. */
  postcodeArea?: string;
}

export const locations: Location[] = [
  {
    id: 'watford',
    name: 'Watford',
    slug: 'watford',
    county: 'Hertfordshire',
    description: 'Watford is a vibrant town in Hertfordshire, known for its excellent transport links to London, thriving business community, and diverse economy. With a mix of retail, service, and technology businesses, Watford offers a dynamic environment for companies looking to establish or expand their online presence.',
    businessFocus: 'Watford has a diverse business landscape with a strong retail sector, professional services, and growing technology companies. The town center hosts numerous small to medium-sized businesses that benefit from both local customers and visitors from surrounding areas.',
    nearbyAreas: ['Bushey', 'Rickmansworth', 'Borehamwood', 'St. Albans'],
    population: 'Approximately 96,800',
    keyIndustries: ['Retail', 'Professional Services', 'Technology', 'Healthcare', 'Entertainment'],
    webDesignFocus: 'Watford businesses compete in one of Hertfordshire\'s most dynamic markets. A professional, high-performance website helps you stand out, attract local customers, and make a strong first impression in Watford and surrounding areas like Bushey and Rickmansworth.',
    webDesignBenefits: [
      'Custom website designed to reflect your Watford business',
      'Mobile-responsive design for customers on the go',
      'Fast-loading pages that keep visitors engaged',
      'Built to attract Watford\'s 96,800 residents as your customer base',
    ],
  },
  {
    id: 'hemel-hempstead',
    name: 'Hemel Hempstead',
    slug: 'hemel-hempstead',
    county: 'Hertfordshire',
    description: 'Hemel Hempstead is a thriving new town in Hertfordshire with a strong business presence, particularly in the industrial and commercial sectors. Its strategic location near the M1 and M25 motorways makes it an ideal location for businesses serving both local and national markets.',
    businessFocus: 'Hemel Hempstead features several business parks and industrial areas, including Maylands Business Park, which is home to numerous companies across various sectors. The town has a mix of large corporations and small to medium enterprises.',
    nearbyAreas: ['St. Albans', 'Berkhamsted', 'Kings Langley', 'Tring'],
    population: 'Approximately 97,500',
    keyIndustries: ['Manufacturing', 'Logistics', 'Technology', 'Retail', 'Construction'],
    webDesignFocus: 'Hemel Hempstead\'s competitive business environment demands a professional online presence. We build websites that help your business attract customers from Maylands Business Park and surrounding areas, and stand out in this thriving market.',
    webDesignBenefits: [
      'Professional website tailored to Hemel Hempstead businesses',
      'Showcase your services to Maylands Business Park clients',
      'Modern design that builds trust with local customers',
      'Attract customers from Berkhamsted and St. Albans',
    ],
  },
  {
    id: 'stevenage',
    name: 'Stevenage',
    slug: 'stevenage',
    county: 'Hertfordshire',
    description: 'Stevenage is a significant town in Hertfordshire with a strong heritage in technology and engineering. As the first new town designated under the New Towns Act 1946, it has developed into an important commercial center with excellent transport links and a diverse business community.',
    businessFocus: 'Stevenage is known for its technology and engineering sectors, with several major companies having headquarters or significant operations in the area. The Stevenage Bioscience Catalyst and Gunnels Wood industrial area are key business hubs.',
    nearbyAreas: ['Hitchin', 'Letchworth Garden City', 'Welwyn Garden City', 'Knebworth'],
    population: 'Approximately 87,800',
    keyIndustries: ['Aerospace', 'Pharmaceuticals', 'Biotechnology', 'Engineering', 'Technology'],
    webDesignFocus: 'Stevenage\'s technology and engineering heritage means businesses here need a website that matches their professionalism. We build high-quality websites that help you reach the town\'s professional workforce and stand out in this competitive tech hub.',
    webDesignBenefits: [
      'Websites built to impress Stevenage\'s tech-savvy audience',
      'Professional design for Bioscience Catalyst and Gunnels Wood businesses',
      'Fast, modern websites that reflect your industry expertise',
      'Reach nearby Hitchin and Letchworth customers online',
    ],
  },
  {
    id: 'st-albans',
    name: 'St. Albans',
    slug: 'st-albans',
    county: 'Hertfordshire',
    postcodeArea: 'AL1',
    description: 'St Albans is Hertfordshire\'s historic cathedral city — 20 miles north-west of London, 8 miles south-west of Welwyn Garden City and 11 miles south-east of Luton. It was the first major town on the Roman road of Watling Street and became the Roman city of Verulamium; today the cathedral, Verulamium Park and the medieval city centre attract both tourists and a thriving professional-services economy. The 2021 census recorded an urban population of 82,146; the full St Albans local-authority district extends to Harpenden, Wheathampstead and Redbourn. St Albans is the most professional-services-dominated town in Hertfordshire by some distance — and the most direct competitor to London agencies and consultancies for SME spend.',
    businessFocus: 'The St Albans economy is defined by professional services. Per ONS UK Business Counts 2025, 2,125 of the 8,200 business units in the St Albans local authority — over 1 in 4 — operate in scientific, technical and professional services (solicitors, accountants, consultancies, architects, design firms). Add Information & communication (945 firms) and the city has the highest concentration of office-based, white-collar SMEs in the county. The retail and hospitality heart sits across St Peter\'s Street (the city\'s north-south spine), Market Place (with twice-weekly Wednesday and Saturday markets dating back to the medieval period), French Row, and Holywell Hill running south toward the cathedral. The Maltings shopping centre provides the indoor retail anchor. Hat manufacturing and inter-war electronics were historic industries; today\'s commercial base is overwhelmingly office-, retail- and hospitality-led.',
    nearbyAreas: ['Harpenden', 'Hatfield', 'Hemel Hempstead', 'Radlett'],
    population: 'Approximately 82,146 (2021 census urban area)',
    keyIndustries: ['Professional Services', 'Information & Communication', 'Construction', 'Retail', 'Administrative & Support'],
    webDesignFocus: 'St Albans is one of Hertfordshire\'s most competitive markets — local SMEs compete directly against London agencies and consultancies. A professionally designed website gives you the edge: London-grade execution, Hertfordshire pricing, and a team that actually understands St Albans and AL1.',
    webDesignBenefits: [
      'Premium website design that rivals London agencies',
      'Tailored to the affluent St Albans professional-services market',
      'Showcase your business with stunning visuals and fast performance',
      'Local web design team who understands the St Albans market',
    ],
    businessLandscape: {
      localAuthority: 'St Albans',
      totalBusinesses: 8200,
      year: 2025,
      microBusinessPct: 91,
      topSectors: [
        { label: 'Professional, scientific & technical', count: 2125 },
        { label: 'Construction', count: 965 },
        { label: 'Information & communication', count: 945 },
        { label: 'Wholesale & retail trade', count: 885 },
        { label: 'Administrative & support services', count: 750 },
        { label: 'Real estate', count: 365 },
      ],
      sourceUrl: 'https://www.nomisweb.co.uk/datasets/idbrlu',
      postcodeActiveCompanies: 4521,
      postcodeNewLast12Months: 410,
      companiesHouseAsOf: '2026-05-18',
    },
    commercialAreas: [
      {
        name: 'St Peter\'s Street',
        type: 'Primary retail thoroughfare',
        description: 'The city\'s main north-south spine, running from the Clock Tower up past the Town Hall toward the Civic Centre. National chains alongside independent retailers and food and beverage. The dominant retail address in AL1 and the natural anchor for "[shop / service] St Albans" search queries.',
      },
      {
        name: 'Market Place + French Row',
        type: 'Historic medieval retail core',
        description: 'Weekly markets have run in Market Place since they were founded by Abbot Ulsinus — Wednesdays and Saturdays still draw substantial footfall. French Row, the narrow medieval lane running off Market Place toward the Clock Tower, hosts a high concentration of independent shops, cafés and hospitality. Businesses trading here lean into the heritage angle online.',
      },
      {
        name: 'Holywell Hill',
        type: 'Cathedral-side commercial street',
        description: 'The historic high street running south from the Clock Tower toward the Cathedral and Verulamium Park. Samuel Ryder ran his seed packet business from a packing warehouse on Holywell Hill in the 1890s — the same Ryder who later founded the Ryder Cup. Today the street mixes professional services (solicitors, financial advisors), independent retail, and tourism-adjacent businesses serving cathedral and park visitors.',
      },
      {
        name: 'The Maltings Shopping Centre',
        type: 'Modern indoor retail',
        description: 'The city\'s main covered shopping centre, sitting between the railway station and the historic core. Provides the national-chain retail anchor that complements the independent character of St Peter\'s Street and Market Place. Retailers based here compete on both pedestrian footfall and online search for visitors planning a day in the city.',
      },
    ],
    townFAQs: [
      {
        question: 'St Albans businesses compete against London agencies — does your work actually hold up against that?',
        answer: 'That\'s exactly the brief. The 2,125 professional-services firms in the St Albans local authority (ONS 2025) regularly lose pitches not on substance but on the website credibility test — when a London competitor\'s site simply looks more serious. Our Herts Professional and Herts Growth tiers are explicitly built to close that gap: design, performance, and copywriting at parity with EC1 or W1 agencies, at Hertfordshire pricing. Most of our St Albans clients chose us specifically because they\'d already seen our work for other AL1 firms.',
      },
      {
        question: 'I run an accountancy / law / consultancy practice in AL1 — what should I expect?',
        answer: '4,521 active companies are registered to AL1 today, 410 incorporated in the last 12 months (Companies House, 2026-05-18). For a regulated professional-services firm, the website needs to do two jobs at once: (1) convert direct enquiries from existing referrals (so reviews, qualifications and case-studies need prominence), and (2) rank for "[service] St Albans" and "[service] AL1" queries to win net-new business. We build with structured data (LegalService / AccountingService / ProfessionalService schemas), proper trust-signal layout, and a no-fluff content approach that suits how your prospects actually evaluate firms.',
      },
      {
        question: 'My business is in Market Place / on French Row / on Holywell Hill — does the heritage of St Albans matter to a website?',
        answer: 'For independents trading in the historic core, yes — significantly. Your customers (both locals and tourists) often choose you over a chain precisely because of the place. Your website should lean into the location: real photos of the shopfront in context, the city\'s history where it\'s relevant to your story, and clear "find us near the Clock Tower / Cathedral / Market" wayfinding. We help you do that without it feeling forced or "twee".',
      },
      {
        question: 'What does a website cost for a small St Albans business?',
        answer: 'Our Herts Essentials package is designed for the 91% of St Albans-district businesses that are micro (fewer than 10 employees, ONS 2025). Herts Professional steps up for established professional-services firms and busier retailers. Herts Growth is for firms with multiple service lines, multiple locations, or who are running paid advertising alongside the site. Pricing is on the Services page — and is consistently lower than what a comparable London agency would charge for similar quality.',
      },
      {
        question: 'St Albans is large — do you only serve the city centre, or also Harpenden, Wheathampstead, Redbourn?',
        answer: 'We cover the full St Albans local authority district. The AL1 city-centre core gets dedicated SEO work, but we also build for businesses based in Harpenden (AL5), Wheathampstead (AL4), Redbourn (AL3) and elsewhere across the district. Our local SEO targets the specific postcode districts your customers actually search in — not a single town name.',
      },
    ],
  },
  {
    id: 'bishops-stortford',
    name: 'Bishop\'s Stortford',
    slug: 'bishops-stortford',
    county: 'Hertfordshire',
    description: 'Bishop\'s Stortford is a historic market town in Hertfordshire, located near Stansted Airport. Its strategic location and excellent transport links make it an attractive location for businesses, particularly those in the service and logistics sectors.',
    businessFocus: 'Bishop\'s Stortford benefits from its proximity to Stansted Airport, which has fostered growth in travel-related businesses, logistics, and hospitality. The town center hosts numerous independent retailers and service providers.',
    nearbyAreas: ['Sawbridgeworth', 'Stansted Mountfitchet', 'Great Dunmow', 'Harlow'],
    population: 'Approximately 40,000',
    keyIndustries: ['Aviation Services', 'Logistics', 'Retail', 'Hospitality', 'Professional Services'],
  },
  {
    id: 'cheshunt',
    name: 'Cheshunt',
    slug: 'cheshunt',
    county: 'Hertfordshire',
    postcodeArea: 'EN8',
    description: 'Cheshunt is a town in the Borough of Broxbourne, sitting on the River Lea and Lee Navigation in the London commuter belt — 13 miles north of central London and bordering the Lee Valley Park. The 2021 census recorded a Cheshunt built-up area population of 43,680, making it one of the larger towns in south-east Hertfordshire. The town\'s economy reflects its position: a heavy construction and trades base serving both Hertfordshire and the M25 corridor, a substantial retail footprint anchored by the Brookfield retail park, and a growing tech-infrastructure layer following Google\'s decision to open its first UK data centre at the Theobalds Business Park in 2025.',
    businessFocus: 'Cheshunt\'s commercial geography is unusually well-defined. The historic retail core sits around the Old Pond junction (where Turners Hill meets College Road) — classed as a district centre by Broxbourne Borough Council. The much larger Brookfield retail park, on the north side of town adjoining the A10, is the modern shopping anchor; planning permission was granted in 2025 for a "Brookfield Riverside" town-centre expansion coupled with the 1,250-home Brookfield Garden Village to its west. The Theobalds Business Park (A10 / Lieutenant Ellis Way) offers modern offices and small-business enterprise space, and now hosts Google\'s first UK data centre. Delamare Road has light-industrial heritage — Lotus Cars was based there from 1959-1966, manufacturing the Lotus 23B. Retail was the single largest employment sector in Broxbourne in 2021, accounting for 23.5% of jobs — well above the 14.4% Hertfordshire average.',
    nearbyAreas: ['Waltham Cross', 'Hoddesdon', 'Enfield', 'Waltham Abbey'],
    population: 'Approximately 43,680 (2021 census built-up area)',
    keyIndustries: ['Construction', 'Retail', 'Professional Services', 'Administrative & Support', 'Logistics'],
    businessLandscape: {
      localAuthority: 'Broxbourne',
      totalBusinesses: 4430,
      year: 2025,
      microBusinessPct: 92,
      topSectors: [
        { label: 'Construction', count: 1115 },
        { label: 'Wholesale & retail trade', count: 705 },
        { label: 'Professional, scientific & technical', count: 535 },
        { label: 'Administrative & support services', count: 415 },
        { label: 'Information & communication', count: 225 },
        { label: 'Accommodation & food services', count: 210 },
      ],
      sourceUrl: 'https://www.nomisweb.co.uk/datasets/idbrlu',
      postcodeActiveCompanies: 4740,
      postcodeNewLast12Months: 661,
      companiesHouseAsOf: '2026-05-18',
    },
    commercialAreas: [
      {
        name: 'Brookfield retail park (A10)',
        type: 'Major retail destination',
        description: 'The dominant shopping anchor on the north side of Cheshunt, off the A10. Planning was granted in 2025 for the "Brookfield Riverside" expansion to turn the park into a new town centre, alongside the 1,250-home Brookfield Garden Village to its west — a multi-year change that will reshape retail and service demand in EN8.',
      },
      {
        name: 'Old Pond historic retail core',
        type: 'District centre (Turners Hill / College Road)',
        description: 'The original retail heart of Cheshunt, at the Turners Hill and College Road junction. Officially classed as a district centre by Broxbourne Borough Council — smaller in scale than the borough\'s designated town centres at Waltham Cross and Hoddesdon. Independent retailers, food and beverage, and local services dominate.',
      },
      {
        name: 'Theobalds Business Park',
        type: 'Modern offices + data centre',
        description: 'A modern development at the A10 / Lieutenant Ellis Way junction, comprising offices, warehouses and an enterprise centre designed for SMEs. Notably, Google\'s first UK data centre opened on the site in 2025 — bringing high-skill tech-infrastructure activity into Cheshunt\'s previously trade-dominated economy.',
      },
      {
        name: 'Delamare Road industrial corridor',
        type: 'Light industrial + automotive heritage',
        description: 'The historic industrial belt where Lotus Cars and Team Lotus operated from 1959 to 1966 (manufacturing the Lotus 23B among others). Today the corridor is dominated by light industry, trade counters, and automotive specialists — feeding the 1,115-strong construction sector that makes Broxbourne unusually trades-heavy.',
      },
    ],
    townFAQs: [
      {
        question: 'Cheshunt has a huge construction sector — do you actually understand sites for trades?',
        answer: 'Yes. The 1,115 construction firms in Broxbourne (ONS UK Business Counts 2025) account for around 25% of all business units in the local authority — far higher than the Hertfordshire average, and a defining feature of the local economy. We build trade sites that match how trades actually win work: clear service-area maps (EN8 + the M25 J25 corridor), accreditation badges (Gas Safe, NICEIC, TrustMark, Checkatrade), real reviews, before/after gallery, and quote-request forms designed for phone-first leads. Generic template websites lose work for trades; ours don\'t.',
      },
      {
        question: 'My business is at the Brookfield retail park — does that mean my website strategy is different from a town-centre business?',
        answer: 'Yes. Brookfield draws a wider catchment than the Old Pond town-centre area — including drivers from across south Hertfordshire and north London. A retail-park-anchored site should rank for broader category queries ("[product] near A10", "[service] Hertfordshire") and convert on parking, opening hours and product availability. With Brookfield Riverside expanding under 2025 planning permission, retailers there should be building for a 5-year horizon, not a single trading year.',
      },
      {
        question: 'I run a small office at Theobalds Business Park — is the data-centre news relevant to my business?',
        answer: 'Indirectly, yes. Google opening its first UK data centre at Theobalds in 2025 raises the local profile of EN8 as a tech-infrastructure location, and is likely to draw adjacent businesses (managed services, networking, security consultancies). For a small office at Theobalds, the marketing angle is genuine: "based at the same business park as Google\'s UK data centre" is a credible differentiator vs competitors operating from a residential address. We help you use the signal without overclaiming.',
      },
      {
        question: 'What does a website cost for a Cheshunt SME?',
        answer: 'Our Herts Essentials package starts at our entry monthly tier — designed for sole traders and micro-businesses (92% of Broxbourne businesses are micro per ONS 2025). Herts Professional suits established trades and small office-based firms; Herts Growth is for businesses competing on multiple service lines or geographies. Most Cheshunt clients we work with sit in Essentials or Professional. See the Services page for current pricing.',
      },
      {
        question: 'Do you also work with retail and hospitality businesses in EN8?',
        answer: 'Yes — retail is the single largest employment sector in Broxbourne (23.5% of jobs in 2021, vs Hertfordshire average 14.4%). We build retail and hospitality sites that work hard on local search ("[shop type] EN8", "[restaurant] near Brookfield"), include direct-booking or order-online integration where it makes sense, and bake in trust signals (real photos, Google reviews surfaced on-page, honest hours). With Brookfield Riverside on the horizon, getting your online presence ahead of new competition is sensible now.',
      },
    ],
  },
  {
    id: 'letchworth-garden-city',
    name: 'Letchworth Garden City',
    slug: 'letchworth-garden-city',
    county: 'Hertfordshire',
    postcodeArea: 'SG6',
    description: 'Letchworth Garden City is the world\'s first garden city — founded in 1903 on Ebenezer Howard\'s plan and built around a deliberate separation of housing, industry and green space. That blueprint still shapes how local business runs today. The original industrial belt east of the town centre (Works Road, Pixmore Avenue, the Spirella Building) is now home to a long tail of small office-based firms, makers and creative studios rather than the corset factories, parachute makers and tabulating-machine plants that put Letchworth on the map in the early 20th century.',
    businessFocus: 'Letchworth\'s economy shifted out of large-scale manufacturing through the 1970s and 80s — Spirella, ICL and Borg-Warner all closed their factories by 1989 — and the vacated industrial sites were redeveloped as business parks and serviced offices. The result today is a town dominated by small firms: independent retailers along Eastcheap and Leys Avenue, professional services clustered near the railway station, and light manufacturing and creative workshops on the historic Works Road industrial estate.',
    nearbyAreas: ['Hitchin', 'Baldock', 'Stevenage', 'Biggleswade'],
    population: 'Approximately 33,990 (2021 census)',
    keyIndustries: ['Professional Services', 'Construction', 'Retail', 'Creative Industries', 'Light Manufacturing'],
    businessLandscape: {
      localAuthority: 'North Hertfordshire',
      totalBusinesses: 6205,
      year: 2025,
      microBusinessPct: 89,
      topSectors: [
        { label: 'Professional, scientific & technical', count: 1195 },
        { label: 'Wholesale & retail trade', count: 845 },
        { label: 'Construction', count: 830 },
        { label: 'Information & communication', count: 560 },
        { label: 'Administrative & support services', count: 500 },
        { label: 'Manufacturing', count: 345 },
      ],
      sourceUrl: 'https://www.nomisweb.co.uk/datasets/idbrlu',
      postcodeActiveCompanies: 2654,
      postcodeNewLast12Months: 279,
      companiesHouseAsOf: '2026-05-18',
    },
    commercialAreas: [
      {
        name: 'Works Road industrial estate',
        type: 'Historic industrial belt',
        description: 'The eastern industrial corridor along Works Road and Pixmore Avenue was Letchworth\'s original manufacturing zone. Today it hosts a mix of light industry, trade counters, automotive specialists and creative workshops. Companies registered here typically operate in SIC sections C (Manufacturing) and G (Wholesale & retail trade).',
      },
      {
        name: 'The Spirella Building',
        type: 'Heritage commercial hub',
        description: 'Cecil Hignett\'s Arts and Crafts factory (completed 1920, locally known as "Castle Corset") was redeveloped into managed offices in the 1990s. It now houses around 50 small businesses — primarily professional services, creative agencies and consultancies — making it the most distinctive office address in the town.',
      },
      {
        name: 'Eastcheap and Leys Avenue',
        type: 'Town-centre retail',
        description: 'The main commercial high street, designed as a single retail spine in the original 1903 masterplan. Dominated by independent retailers, food and beverage, and personal services — the kind of trader who needs a website that converts foot-traffic searchers into walk-ins.',
      },
      {
        name: 'Letchworth Business Park (Blackhorse Road area)',
        type: 'Modern business park',
        description: 'Newer-build serviced offices and light industrial units on the northern edge of the original industrial belt. Tenant mix skews toward administrative services, IT firms and trades counters serving North Hertfordshire.',
      },
    ],
    townFAQs: [
      {
        question: 'I run a small business in Letchworth — is this site relevant to me?',
        answer: '89% of businesses in North Hertfordshire (the local authority covering Letchworth) employ fewer than 10 people, per the 2025 ONS UK Business Counts. That micro and small-business tier is exactly who we build websites for. If you trade from Works Road, the Spirella Building, Eastcheap or anywhere within SG6, our packages are sized for you.',
      },
      {
        question: 'What does a website cost for a Letchworth business?',
        answer: 'Our entry-level Herts Essentials package starts at a fixed monthly figure designed for sole traders and micro-businesses, with Herts Professional and Herts Growth tiers for firms with more service depth or higher volumes. See the Services page for current pricing. Most Letchworth clients we work with sit in the Essentials or Professional tier.',
      },
      {
        question: 'Do you work with manufacturers and trades on the Works Road estate?',
        answer: 'Yes. Construction and Manufacturing together account for around 1,175 of the 6,205 business units in North Hertfordshire (ONS 2025), and a high share sit on the historic Works Road / Pixmore Avenue industrial belt. We build trade-focused sites with clear service area maps, trust signals (insurance, accreditations, real reviews), and quote-request forms designed for phone-first leads.',
      },
      {
        question: 'How do you handle the SG6 area specifically — do you only serve Letchworth town centre?',
        answer: 'We cover the full SG6 postcode area. There are 2,654 active companies registered to SG6 today, with 279 incorporated in the last 12 months (Companies House, 2026-05-18) — that\'s the population we build for. We also work across the rest of North Hertfordshire (Hitchin SG4, Baldock SG7, Knebworth SG3) and the wider county. Local SEO work targets the specific postcode districts you trade in, not just a single town name.',
      },
      {
        question: 'Letchworth has Garden City planning controls — does that affect my website?',
        answer: 'Garden City Heritage Foundation rules govern physical signage, frontages and building works, not your digital presence. That said, we often help heritage-aware businesses (the Spirella tenants, independent retailers on Eastcheap) lean into the Garden City story on their websites — it\'s a genuine differentiator that customers searching from outside the area find compelling.',
      },
    ],
  },
  {
    id: 'hatfield',
    name: 'Hatfield',
    slug: 'hatfield',
    county: 'Hertfordshire',
    description: 'Hatfield is a town in Hertfordshire with a strong aerospace heritage and home to the University of Hertfordshire. This educational presence, combined with good transport links and business parks, makes Hatfield an important center for knowledge-based industries and technology companies.',
    businessFocus: 'Hatfield Business Park, built on the former site of Hatfield Aerodrome, is a major commercial center. The presence of the University of Hertfordshire has fostered growth in research, technology, and education-related businesses.',
    nearbyAreas: ['Welwyn Garden City', 'St. Albans', 'Potters Bar', 'Welham Green'],
    population: 'Approximately 39,000',
    keyIndustries: ['Aerospace', 'Technology', 'Education', 'Research', 'Retail'],
  },
  {
    id: 'hertford',
    name: 'Hertford',
    slug: 'hertford',
    county: 'Hertfordshire',
    description: 'Hertford is the historic county town of Hertfordshire, combining heritage with a vibrant modern business community. Its picturesque setting, good schools, and quality of life make it attractive to businesses and professionals looking for a balance between work and lifestyle.',
    businessFocus: 'Hertford has a diverse business community with a strong presence in professional services, retail, and hospitality. The town center features many independent businesses, while Hertford Business Park hosts larger companies.',
    nearbyAreas: ['Ware', 'Welwyn Garden City', 'Hoddesdon', 'Harlow'],
    population: 'Approximately 26,800',
    keyIndustries: ['Professional Services', 'Retail', 'Hospitality', 'Creative Industries', 'Education'],
    webDesignFocus: 'Hertford businesses face competition from nearby Ware and Welwyn Garden City. A professional website helps you stand out, making sure customers choose your business when they\'re looking for services in Hertford.',
    webDesignBenefits: [
      'Custom website that captures Hertford\'s local character',
      'Professional design that builds trust with customers',
      'Attract customers from nearby Ware and Hoddesdon',
      'Stand out from larger towns while maintaining local appeal',
    ],
  },
  {
    id: 'hitchin',
    name: 'Hitchin',
    slug: 'hitchin',
    county: 'Hertfordshire',
    description: 'Hitchin is a historic market town in Hertfordshire with a thriving business community. Its charming town center, regular markets, and strong sense of community make it an attractive location for independent businesses and service providers.',
    businessFocus: 'Hitchin has a vibrant town center with numerous independent retailers, cafes, and service providers. The Wilbury Way industrial area hosts manufacturing and distribution businesses, while professional services are well-represented throughout the town.',
    nearbyAreas: ['Letchworth Garden City', 'Stevenage', 'Baldock', 'Luton'],
    population: 'Approximately 33,350',
    keyIndustries: ['Retail', 'Professional Services', 'Hospitality', 'Manufacturing', 'Creative Industries'],
    webDesignFocus: 'Hitchin has a vibrant business community and competitive local market. A well-designed website ensures your Hitchin business makes a great first impression, attracting customers from Hitchin, Letchworth, and the surrounding areas.',
    webDesignBenefits: [
      'Beautiful website that reflects Hitchin\'s independent spirit',
      'Designed to attract customers across North Hertfordshire',
      'Mobile-friendly design for on-the-go visitors',
      'Stand out from competitors in Letchworth and Stevenage',
    ],
  },
  {
    id: 'potters-bar',
    name: 'Potters Bar',
    slug: 'potters-bar',
    county: 'Hertfordshire',
    postcodeArea: 'EN6',
    description: 'Potters Bar is a Hertfordshire town 13 miles north of central London, sitting at the southern edge of the county on the Hertsmere/Greater London boundary. The 2021 census recorded 22,536 residents across four wards (Bentley Heath & The Royds, Furzefield, Oakmere and Parkfield); the local population reached 23,325 in 2022. The town\'s character is shaped by its commuter-belt geography — a railway-station-centred town where most working residents head into London but a substantial professional-services and trades base operates locally, serving both Potters Bar itself and the affluent surrounding villages of Brookmans Park, Cuffley and South Mimms.',
    businessFocus: 'Hertsmere — the local authority covering Potters Bar — is unusual in Hertfordshire for the strength of its professional-services and information & communication sectors (Hertsmere also includes Borehamwood\'s Elstree Studios). Locally in Potters Bar, the High Street and Darkes Lane form the retail spine, while professional services (solicitors, accountants, financial advisors, healthcare practices) cluster near the station. The historic 1934 Ritz Cinema site on Darkes Lane was redeveloped into a Tesco supermarket — a microcosm of the town\'s shift from leisure/local-industry to commuter retail. The town does not have a single major industrial estate; instead, smaller commercial and trade-counter units sit on the residential periphery.',
    nearbyAreas: ['Barnet', 'Hatfield', 'Enfield', 'Brookmans Park'],
    population: 'Approximately 23,325 (2022); 22,536 at the 2021 census',
    keyIndustries: ['Professional Services', 'Construction', 'Information & Communication', 'Retail', 'Healthcare'],
    businessLandscape: {
      localAuthority: 'Hertsmere',
      totalBusinesses: 7800,
      year: 2025,
      microBusinessPct: 92,
      topSectors: [
        { label: 'Professional, scientific & technical', count: 1390 },
        { label: 'Construction', count: 1255 },
        { label: 'Wholesale & retail trade', count: 935 },
        { label: 'Information & communication', count: 780 },
        { label: 'Administrative & support services', count: 690 },
        { label: 'Real estate', count: 660 },
      ],
      sourceUrl: 'https://www.nomisweb.co.uk/datasets/idbrlu',
      postcodeActiveCompanies: 5208,
      postcodeNewLast12Months: 514,
      companiesHouseAsOf: '2026-05-18',
    },
    commercialAreas: [
      {
        name: 'High Street',
        type: 'Primary retail thoroughfare',
        description: 'The main shopping spine of Potters Bar. Mixed independent retailers, food and beverage, and local services. A typical EN6 trader on the High Street depends on local foot traffic plus commuters returning from London — a website that converts both audiences matters.',
      },
      {
        name: 'Darkes Lane',
        type: 'Commercial parade + supermarket anchor',
        description: 'Parallel to the High Street, anchored by the modern Tesco (built on the site of the 1934 Ritz Cinema at the Byng Drive corner). Home to professional services offices, beauty and personal-services businesses, and the bus depot — a different commercial character to the High Street.',
      },
      {
        name: 'Station-area professional services cluster',
        type: 'Office and consulting space',
        description: 'The blocks around Potters Bar railway station host the highest concentration of solicitors, accountants, financial advisors and healthcare practices in the town — exactly the sectors that dominate Hertsmere\'s ONS top-sector list (1,390 professional/scientific/technical firms in 2025). These are micro and small firms with strong commuter visibility.',
      },
    ],
    townFAQs: [
      {
        question: 'I run a small business in Potters Bar — do you actually serve EN6 specifically?',
        answer: 'Yes. There are 5,208 active companies registered to EN6 today, with 514 incorporated in the last 12 months (Companies House, 2026-05-18). 92% of businesses across the Hertsmere local authority are micro-businesses (fewer than 10 employees, ONS UK Business Counts 2025) — exactly the tier our packages are built for. Whether you trade from the High Street, Darkes Lane, the station-area offices, or a residential address in Oakmere or Parkfield, we cover EN6 plus the surrounding South Hertfordshire postcodes.',
      },
      {
        question: 'Most Potters Bar businesses are commuter-facing — does that change how you build sites?',
        answer: 'Yes, materially. A Potters Bar business often has two distinct audiences: local residents searching during the day, and London commuters searching from their phone on the train home. We design for both — fast-loading mobile pages, click-to-call buttons that work on the move, opening-hours and parking information visible without scrolling, and clear "we\'re local" trust signals so commuters who could choose a London provider pick you instead.',
      },
      {
        question: 'What\'s the dominant business type around here, and do you work with it?',
        answer: 'Professional services dominate Hertsmere — 1,390 firms in scientific, technical and professional services per ONS 2025, with another 780 in IT/communications. Construction is the second-biggest sector at 1,255 firms (largely trades serving the affluent residential base in Potters Bar, Brookmans Park and Cuffley). We work with both sides — credibility-focused sites for solicitors and accountants who need to look as substantial as any London firm, and lead-focused sites for trades who depend on local search and quick quote requests.',
      },
      {
        question: 'How does proximity to London affect what we should expect from our website?',
        answer: 'It raises the bar. Your customers compare your site against London-agency-built websites every day. Generic templates from £20/month builders are visibly out of place on a Potters Bar professional-services site in 2026. Our Herts Professional and Herts Growth tiers are designed for exactly this competitive context — sites that hold up next to anything an EC1 firm would produce, at Hertfordshire pricing.',
      },
      {
        question: 'Do you support local SEO for Potters Bar specifically, or just generic Hertfordshire?',
        answer: 'Both — and Potters Bar specifically is worth doing properly. EN6 is a distinct search market: shoppers searching "[trade] potters bar" or "[service] EN6" rarely return the same results as broader Hertfordshire queries. Our SEO work targets the specific postcode districts you trade in (EN6 itself, plus the nearby EN7 Cuffley and AL9 Brookmans Park markets) with town-page content and local schema, not just county-level keywords.',
      },
    ],
  },
  {
    id: 'bushey',
    name: 'Bushey',
    slug: 'bushey',
    county: 'Hertfordshire',
    description: 'Bushey is a town in Hertfordshire adjacent to Watford, offering a more residential character while benefiting from proximity to larger commercial centers. Its leafy suburbs and good schools make it attractive to professionals and service-based businesses.',
    businessFocus: 'Bushey has a range of small to medium-sized businesses, particularly in the service sector. The high street features independent retailers and service providers, while some larger businesses are located in dedicated commercial areas.',
    nearbyAreas: ['Watford', 'Stanmore', 'Borehamwood', 'Harrow'],
    population: 'Approximately 24,000',
    keyIndustries: ['Professional Services', 'Retail', 'Healthcare', 'Education', 'Creative Industries'],
  },
  {
    id: 'berkhamsted',
    name: 'Berkhamsted',
    slug: 'berkhamsted',
    county: 'Hertfordshire',
    description: 'Berkhamsted is a historic market town in Hertfordshire, known for its castle, canal, and vibrant high street. Its affluent character and strong sense of community make it particularly attractive to upscale retailers, service providers, and creative businesses.',
    businessFocus: 'Berkhamsted has a thriving high street with many independent businesses alongside some national chains. Professional services, creative industries, and hospitality are well-represented, catering to the town\'s affluent population.',
    nearbyAreas: ['Tring', 'Hemel Hempstead', 'Chesham', 'Amersham'],
    population: 'Approximately 18,500',
    keyIndustries: ['Retail', 'Professional Services', 'Creative Industries', 'Hospitality', 'Education'],
  },
  {
    id: 'harpenden',
    name: 'Harpenden',
    slug: 'harpenden',
    county: 'Hertfordshire',
    description: 'Harpenden is an affluent town in Hertfordshire with excellent transport links to London. Its combination of wealth, good schools, and attractive environment makes it a premium location for businesses serving high-end clients and professional services.',
    businessFocus: 'Harpenden\'s business community is dominated by retail, hospitality, and professional services. The town center features upscale shops, restaurants, and service providers catering to the town\'s affluent population.',
    nearbyAreas: ['St. Albans', 'Luton', 'Wheathampstead', 'Redbourn'],
    population: 'Approximately 30,240',
    keyIndustries: ['Professional Services', 'Finance', 'Retail', 'Hospitality', 'Education'],
  },
  {
    id: 'waltham-cross',
    name: 'Waltham Cross',
    slug: 'waltham-cross',
    county: 'Hertfordshire',
    description: 'Waltham Cross is a town in the Borough of Broxbourne, Hertfordshire, located at the edge of Greater London. Its strategic location near the M25 and proximity to London make it an important commercial center, particularly for logistics and distribution businesses.',
    businessFocus: 'Waltham Cross has a mix of retail, service, and industrial businesses. The Park Plaza and Lea Road industrial areas host numerous companies in manufacturing, distribution, and services.',
    nearbyAreas: ['Cheshunt', 'Enfield', 'Waltham Abbey', 'Hoddesdon'],
    population: 'Approximately 7,600',
    keyIndustries: ['Logistics', 'Retail', 'Manufacturing', 'Services', 'Construction'],
  },
  {
    id: 'radlett',
    name: 'Radlett',
    slug: 'radlett',
    county: 'Hertfordshire',
    description: 'Radlett is an affluent village in Hertfordshire, known for its upscale character and proximity to London. Its wealthy demographic and pleasant environment make it particularly suitable for premium service providers and businesses catering to high-net-worth individuals.',
    businessFocus: 'Radlett has a small but vibrant high street with independent retailers, restaurants, and service providers. Professional services such as financial advisors, legal firms, and property specialists are well-represented.',
    nearbyAreas: ['Borehamwood', 'St. Albans', 'Watford', 'Elstree'],
    population: 'Approximately 8,000',
    keyIndustries: ['Professional Services', 'Finance', 'Retail', 'Hospitality', 'Property'],
  },
  // NEW LOCATIONS - Adding all missing nearby areas
  {
    id: 'rickmansworth',
    name: 'Rickmansworth',
    slug: 'rickmansworth',
    county: 'Hertfordshire',
    description: 'Rickmansworth is an attractive market town in West Hertfordshire, known for its canals, historical architecture, and affluent residential areas. The town offers good transport links to London and hosts a variety of independent businesses alongside some national chains.',
    businessFocus: 'Rickmansworth has a strong local business community with independent retailers, cafes, restaurants, and professional services. The town center benefits from both local trade and tourism related to the canal networks.',
    nearbyAreas: ['Watford', 'Chorleywood', 'Northwood', 'Croxley Green'],
    population: 'Approximately 15,000',
    keyIndustries: ['Retail', 'Professional Services', 'Hospitality', 'Tourism', 'Healthcare'],
  },
  {
    id: 'borehamwood',
    name: 'Borehamwood',
    slug: 'borehamwood',
    county: 'Hertfordshire',
    description: 'Borehamwood is known as the home of the British film industry, with Elstree Studios being a major landmark. The town has excellent transport links to London and a diverse business community spanning entertainment, retail, and professional services.',
    businessFocus: 'Borehamwood\'s economy benefits from its connection to the film and television industry, with many production-related businesses. The town also has a strong retail sector and growing professional services community.',
    nearbyAreas: ['Elstree', 'Bushey', 'Radlett', 'Stanmore'],
    population: 'Approximately 32,000',
    keyIndustries: ['Entertainment', 'Media Production', 'Retail', 'Professional Services', 'Technology'],
  },
  {
    id: 'kings-langley',
    name: 'Kings Langley',
    slug: 'kings-langley',
    county: 'Hertfordshire',
    description: 'Kings Langley is a village in Hertfordshire with a rich history and strong community feel. Located between Hemel Hempstead and Watford, it offers a peaceful business environment with good transport connections to major commercial centers.',
    businessFocus: 'Kings Langley has a mix of local businesses serving the community, with a focus on independent retailers, professional services, and small enterprises. The village benefits from its proximity to larger business centers while maintaining its village character.',
    nearbyAreas: ['Hemel Hempstead', 'Watford', 'Berkhamsted', 'Abbots Langley'],
    population: 'Approximately 5,000',
    keyIndustries: ['Retail', 'Professional Services', 'Agriculture', 'Small Manufacturing', 'Services'],
  },
  {
    id: 'tring',
    name: 'Tring',
    slug: 'tring',
    county: 'Hertfordshire',
    description: 'Tring is a historic market town in Hertfordshire, situated at the foot of the Chiltern Hills. Known for its independent shops, restaurants, and strong community spirit, Tring offers an attractive location for businesses seeking a balance between accessibility and character.',
    businessFocus: 'Tring has a vibrant high street with many independent businesses, including boutique shops, restaurants, and professional services. The town attracts both local customers and visitors exploring the Chilterns area.',
    nearbyAreas: ['Berkhamsted', 'Hemel Hempstead', 'Aylesbury', 'Chesham'],
    population: 'Approximately 12,000',
    keyIndustries: ['Retail', 'Hospitality', 'Professional Services', 'Tourism', 'Agriculture'],
  },
  {
    id: 'knebworth',
    name: 'Knebworth',
    slug: 'knebworth',
    county: 'Hertfordshire',
    description: 'Knebworth is a village in Hertfordshire famous for its historic house and music festivals. Despite its village status, it has good transport links and serves as an attractive location for businesses seeking a prestigious address in a peaceful setting.',
    businessFocus: 'Knebworth\'s business community consists mainly of professional services, small businesses, and enterprises related to tourism and events. The village benefits from its prestigious reputation and proximity to larger commercial centers.',
    nearbyAreas: ['Stevenage', 'Hitchin', 'Welwyn Garden City', 'Hertford'],
    population: 'Approximately 1,500',
    keyIndustries: ['Professional Services', 'Event Management', 'Tourism', 'Retail', 'Property Services'],
  },
  {
    id: 'welwyn-garden-city',
    name: 'Welwyn Garden City',
    slug: 'welwyn-garden-city',
    county: 'Hertfordshire',
    description: 'Welwyn Garden City is a planned town in Hertfordshire, designed as a garden city with wide open spaces and modern amenities. It hosts numerous businesses and has excellent transport links, making it an attractive location for companies of all sizes.',
    businessFocus: 'Welwyn Garden City has several business parks and industrial areas, with a strong presence in manufacturing, technology, and professional services. The town center also features a good mix of retail and service businesses.',
    nearbyAreas: ['Hatfield', 'Hertford', 'Stevenage', 'Welham Green'],
    population: 'Approximately 51,000',
    keyIndustries: ['Manufacturing', 'Technology', 'Retail', 'Professional Services', 'Pharmaceuticals'],
  },
  {
    id: 'sawbridgeworth',
    name: 'Sawbridgeworth',
    slug: 'sawbridgeworth',
    county: 'Hertfordshire',
    description: 'Sawbridgeworth is a market town in East Hertfordshire with a rich history dating back to Saxon times. The town has maintained its historical character while developing modern business facilities, offering an attractive environment for various enterprises.',
    businessFocus: 'Sawbridgeworth has a strong local business community with independent shops, restaurants, and service providers. The town benefits from its proximity to both Harlow and Bishop\'s Stortford.',
    nearbyAreas: ['Bishop\'s Stortford', 'Harlow', 'Stansted Mountfitchet', 'Much Hadham'],
    population: 'Approximately 8,700',
    keyIndustries: ['Retail', 'Agriculture', 'Professional Services', 'Manufacturing', 'Hospitality'],
  },
  {
    id: 'stansted-mountfitchet',
    name: 'Stansted Mountfitchet',
    slug: 'stansted-mountfitchet',
    county: 'Essex',
    description: 'Stansted Mountfitchet is a village in Essex, close to Stansted Airport and the Hertfordshire border. Its proximity to the airport makes it attractive for aviation-related businesses and those needing good international connections.',
    businessFocus: 'The village benefits from its location near Stansted Airport, with businesses in aviation services, logistics, and hospitality. It also has a growing community of small businesses and professional services.',
    nearbyAreas: ['Bishop\'s Stortford', 'Sawbridgeworth', 'Stansted Airport', 'Great Dunmow'],
    population: 'Approximately 6,000',
    keyIndustries: ['Aviation Services', 'Logistics', 'Professional Services', 'Retail', 'Hospitality'],
  },
  {
    id: 'great-dunmow',
    name: 'Great Dunmow',
    slug: 'great-dunmow',
    county: 'Essex',
    description: 'Great Dunmow is a historic market town in Essex, close to the Hertfordshire border. Known for its traditional market and strong community, it offers a blend of historical charm and modern business opportunities.',
    businessFocus: 'Great Dunmow has a thriving high street with independent businesses, market traders, and various professional services. The town benefits from both local trade and its position on major transport routes.',
    nearbyAreas: ['Bishop\'s Stortford', 'Stansted Mountfitchet', 'Braintree', 'Chelmsford'],
    population: 'Approximately 8,000',
    keyIndustries: ['Retail', 'Agriculture', 'Professional Services', 'Manufacturing', 'Market Trading'],
  },
  {
    id: 'harlow',
    name: 'Harlow',
    slug: 'harlow',
    county: 'Essex',
    description: 'Harlow is a new town in Essex, designed as a post-war new town with modern infrastructure and business facilities. Its strategic location between London and Cambridge, with excellent transport links, makes it attractive for technology and business services companies.',
    businessFocus: 'Harlow is known for its technology sector, with several major companies and start-ups based in the area. The town has modern business parks and good facilities for companies of all sizes.',
    nearbyAreas: ['Bishop\'s Stortford', 'Sawbridgeworth', 'Hertford', 'Epping'],
    population: 'Approximately 87,000',
    keyIndustries: ['Technology', 'Professional Services', 'Retail', 'Healthcare', 'Education'],
  },
  {
    id: 'waltham-abbey',
    name: 'Waltham Abbey',
    slug: 'waltham-abbey',
    county: 'Essex',
    description: 'Waltham Abbey is a town in Essex on the Greenwich Meridian, between the M25 and Epping Forest. With its mix of historical significance and modern amenities, it provides an attractive location for businesses seeking proximity to London.',
    businessFocus: 'Waltham Abbey has a diverse business community with retail, professional services, and light industrial businesses. The town benefits from its strategic location and good transport links.',
    nearbyAreas: ['Cheshunt', 'Waltham Cross', 'Epping', 'Enfield'],
    population: 'Approximately 22,000',
    keyIndustries: ['Retail', 'Professional Services', 'Light Manufacturing', 'Logistics', 'Tourism'],
  },
  {
    id: 'biggleswade',
    name: 'Biggleswade',
    slug: 'biggleswade',
    county: 'Bedfordshire',
    description: 'Biggleswade is a market town in Bedfordshire, close to the Hertfordshire border. Known for its market heritage and good transport links, it offers attractive opportunities for businesses serving the wider region.',
    businessFocus: 'Biggleswade has a strong market tradition and local business community, with particular strength in agriculture-related industries, retail, and professional services.',
    nearbyAreas: ['Letchworth Garden City', 'Sandy', 'Bedford', 'Hitchin'],
    population: 'Approximately 16,500',
    keyIndustries: ['Agriculture', 'Retail', 'Professional Services', 'Manufacturing', 'Logistics'],
  },
  {
    id: 'baldock',
    name: 'Baldock',
    slug: 'baldock',
    county: 'Hertfordshire',
    description: 'Baldock is a historic market town in North Hertfordshire, known for its medieval street pattern and strong sense of community. The town offers a blend of traditional charm and modern business opportunities.',
    businessFocus: 'Baldock has a thriving high street with independent businesses, alongside some national chains. The town benefits from its location on the A1(M) and good rail connections.',
    nearbyAreas: ['Letchworth Garden City', 'Hitchin', 'Stevenage', 'Royston'],
    population: 'Approximately 10,000',
    keyIndustries: ['Retail', 'Professional Services', 'Manufacturing', 'Agriculture', 'Logistics'],
  },
  {
    id: 'welham-green',
    name: 'Welham Green',
    slug: 'welham-green',
    county: 'Hertfordshire',
    description: 'Welham Green is a village in Hertfordshire with good rail connections to London. Its residential character and proximity to business centers make it attractive for professionals and small businesses.',
    businessFocus: 'Welham Green has a small but active business community, mainly comprising local service providers, professional services, and small retail businesses serving the local community.',
    nearbyAreas: ['Hatfield', 'Welwyn Garden City', 'Potters Bar', 'Brookmans Park'],
    population: 'Approximately 3,500',
    keyIndustries: ['Professional Services', 'Retail', 'Healthcare', 'Education', 'Local Services'],
  },
  {
    id: 'ware',
    name: 'Ware',
    slug: 'ware',
    county: 'Hertfordshire',
    description: 'Ware is an ancient market town in Hertfordshire on the River Lea, with a rich history and strong business community. The town combines historical charm with modern amenities and good transport links.',
    businessFocus: 'Ware has a vibrant high street with a mix of independent and chain businesses. The town also has several business parks and industrial areas, supporting a diverse range of enterprises.',
    nearbyAreas: ['Hertford', 'Hoddesdon', 'Hertford Heath', 'Great Amwell'],
    population: 'Approximately 18,000',
    keyIndustries: ['Retail', 'Professional Services', 'Manufacturing', 'Technology', 'Hospitality'],
  },
  {
    id: 'luton',
    name: 'Luton',
    slug: 'luton',
    county: 'Bedfordshire',
    description: 'Luton is a large town in Bedfordshire with Luton Airport being a major economic driver. The town has a diverse business community and excellent transport links, making it attractive for various industries.',
    businessFocus: 'Luton\'s economy is significantly influenced by the airport, with strong sectors in aviation, logistics, and hospitality. The town also has a growing technology sector and diverse retail offerings.',
    nearbyAreas: ['Harpenden', 'Hitchin', 'Dunstable', 'St. Albans'],
    population: 'Approximately 213,000',
    keyIndustries: ['Aviation', 'Logistics', 'Technology', 'Retail', 'Manufacturing'],
  },
  {
    id: 'barnet',
    name: 'Barnet',
    slug: 'barnet',
    county: 'Greater London',
    description: 'Barnet is a suburban area in North London with good transport links and a thriving business community. Its location provides easy access to both central London and Hertfordshire, making it attractive for various businesses.',
    businessFocus: 'Barnet has a diverse business landscape with strong retail, professional services, and technology sectors. The area benefits from its proximity to London while maintaining a more suburban character.',
    nearbyAreas: ['Potters Bar', 'Enfield', 'Finchley', 'Edgware'],
    population: 'Approximately 86,000',
    keyIndustries: ['Professional Services', 'Retail', 'Technology', 'Healthcare', 'Education'],
  },
  {
    id: 'brookmans-park',
    name: 'Brookmans Park',
    slug: 'brookmans-park',
    county: 'Hertfordshire',
    description: 'Brookmans Park is an affluent residential area in Hertfordshire with good rail connections to London. Known for its upscale character, it attracts premium service providers and professionals.',
    businessFocus: 'Brookmans Park has a small but quality-focused business community, with professional services, boutique retail, and upscale service providers catering to the affluent local population.',
    nearbyAreas: ['Potters Bar', 'Welham Green', 'Hatfield', 'Cuffley'],
    population: 'Approximately 3,000',
    keyIndustries: ['Professional Services', 'Finance', 'Premium Retail', 'Healthcare', 'Property Services'],
  },
  {
    id: 'stanmore',
    name: 'Stanmore',
    slug: 'stanmore',
    county: 'Greater London',
    description: 'Stanmore is an affluent area in North West London with a village-like character. Its proximity to both London and Hertfordshire, combined with good transport links, makes it attractive for businesses and professionals.',
    businessFocus: 'Stanmore has a strong local business community with professional services, upscale retail, and hospitality businesses. The area benefits from both local trade and proximity to central London.',
    nearbyAreas: ['Bushey', 'Watford', 'Harrow', 'Edgware'],
    population: 'Approximately 15,000',
    keyIndustries: ['Professional Services', 'Retail', 'Healthcare', 'Finance', 'Property'],
  },
  {
    id: 'harrow',
    name: 'Harrow',
    slug: 'harrow',
    county: 'Greater London',
    description: 'Harrow is a large suburban area in North West London, known for Harrow School and its diverse business community. The area offers good transport links and a mix of residential and commercial opportunities.',
    businessFocus: 'Harrow has a diverse business community with strong retail, professional services, and education sectors. The presence of Harrow School adds to the area\'s educational excellence reputation.',
    nearbyAreas: ['Bushey', 'Stanmore', 'Pinner', 'Northwood'],
    population: 'Approximately 149,000',
    keyIndustries: ['Education', 'Professional Services', 'Retail', 'Healthcare', 'Financial Services'],
  },
  {
    id: 'chesham',
    name: 'Chesham',
    slug: 'chesham',
    county: 'Buckinghamshire',
    description: 'Chesham is a market town in the Chiltern Hills of Buckinghamshire, close to the Hertfordshire border. Known for its traditional market and beautiful surrounding countryside, it offers an attractive location for various businesses.',
    businessFocus: 'Chesham has a strong local business community with independent retailers, market traders, and professional services. The town benefits from tourism related to the Chiltern Hills.',
    nearbyAreas: ['Amersham', 'Berkhamsted', 'Rickmansworth', 'Tring'],
    population: 'Approximately 21,000',
    keyIndustries: ['Retail', 'Tourism', 'Professional Services', 'Agriculture', 'Manufacturing'],
  },
  {
    id: 'amersham',
    name: 'Amersham',
    slug: 'amersham',
    county: 'Buckinghamshire',
    description: 'Amersham is a historic market town in Buckinghamshire, consisting of Old Amersham with its medieval character and Amersham-on-the-Hill with modern amenities. The town offers excellent transport links to London.',
    businessFocus: 'Amersham has a diverse business community with a mix of traditional and modern enterprises. The town benefits from its heritage tourism while supporting contemporary business needs.',
    nearbyAreas: ['Chesham', 'Berkhamsted', 'Gerrards Cross', 'High Wycombe'],
    population: 'Approximately 17,000',
    keyIndustries: ['Professional Services', 'Retail', 'Tourism', 'Technology', 'Finance'],
  },
  {
    id: 'wheathampstead',
    name: 'Wheathampstead',
    slug: 'wheathampstead',
    county: 'Hertfordshire',
    description: 'Wheathampstead is a village in Hertfordshire with a rich history and strong community spirit. Located near St. Albans, it offers a peaceful business environment with good access to larger commercial centers.',
    businessFocus: 'Wheathampstead has a small but active business community focused on serving the local population, with independent retailers, professional services, and hospitality businesses.',
    nearbyAreas: ['St. Albans', 'Harpenden', 'Redbourn', 'Welwyn Garden City'],
    population: 'Approximately 6,000',
    keyIndustries: ['Professional Services', 'Retail', 'Agriculture', 'Hospitality', 'Local Services'],
  },
  {
    id: 'redbourn',
    name: 'Redbourn',
    slug: 'redbourn',
    county: 'Hertfordshire',
    description: 'Redbourn is a village in Hertfordshire with a strong community feel and good connections to both St. Albans and Luton. The village maintains its rural character while supporting various local businesses.',
    businessFocus: 'Redbourn has a close-knit business community with local shops, pubs, and service providers. The village benefits from its proximity to larger towns while maintaining its village character.',
    nearbyAreas: ['St. Albans', 'Harpenden', 'Hemel Hempstead', 'Wheathampstead'],
    population: 'Approximately 5,500',
    keyIndustries: ['Retail', 'Professional Services', 'Agriculture', 'Hospitality', 'Local Services'],
  },
  {
    id: 'elstree',
    name: 'Elstree',
    slug: 'elstree',
    county: 'Hertfordshire',
    description: 'Elstree is a village in Hertfordshire famous for Elstree Studios and its connection to the film and television industry. Despite its small size, it has significant economic importance in the entertainment sector.',
    businessFocus: 'Elstree\'s economy is dominated by the entertainment industry, with film and television production being major employers. The village also has various support services for the entertainment industry.',
    nearbyAreas: ['Borehamwood', 'Radlett', 'Bushey', 'Watford'],
    population: 'Approximately 5,000',
    keyIndustries: ['Entertainment', 'Media Production', 'Professional Services', 'Tourism', 'Creative Industries'],
  },
  {
    id: 'enfield',
    name: 'Enfield',
    slug: 'enfield',
    county: 'Greater London',
    description: 'Enfield is a large suburban area in North London with a diverse business community and good transport links. Its location provides easy access to both central London and Hertfordshire.',
    businessFocus: 'Enfield has a broad business base including retail, manufacturing, professional services, and technology. The area benefits from its strategic location and diverse population.',
    nearbyAreas: ['Potters Bar', 'Cheshunt', 'Barnet', 'Waltham Cross'],
    population: 'Approximately 156,000',
    keyIndustries: ['Manufacturing', 'Retail', 'Professional Services', 'Technology', 'Healthcare'],
  },
  {
    id: 'hoddesdon',
    name: 'Hoddesdon',
    slug: 'hoddesdon',
    county: 'Hertfordshire',
    description: 'Hoddesdon is a town in the Borough of Broxbourne, Hertfordshire, located in the Lea Valley. The town has good transport links and a mix of residential and commercial areas.',
    businessFocus: 'Hoddesdon has a diverse business community with retail, professional services, and some light industry. The town center has undergone recent regeneration to support local businesses.',
    nearbyAreas: ['Waltham Cross', 'Cheshunt', 'Hertford', 'Ware'],
    population: 'Approximately 42,000',
    keyIndustries: ['Retail', 'Professional Services', 'Technology', 'Manufacturing', 'Logistics'],
  },
];

export function getAllLocationSlugs() {
  return locations.map(location => location.slug);
}

export function getLocationBySlug(slug: string) {
  return locations.find(location => location.slug === slug);
}
